const Develop = [
  {
    category: "Develop",
    subCategory: "",
    id: 0,
    title: "마크다운 테스트",
    date: new Date("2021-08-25"),
    content: "store/article_data/Develop/20210825_markdown_test.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 1,
    title: "[GitHub Blog 개발기] 정리할 내용 목록",
    date: new Date("2021-09-01"),
    content: "store/article_data/Develop/20210901_GitHubBlog.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 2,
    title: "[GitHub Blog 개발기] 개발일지",
    date: new Date("2021-09-27"),
    content: "store/article_data/Develop/20210927_GitHubBlog.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 3,
    title: "[GitHub Blog 개발기] Markdown 적용 및 Require 함수",
    date: new Date("2021-09-28"),
    content: "store/article_data/Develop/20210928_GitHubBlog.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 4,
    title: "[GitHub Blog 개발기] 구글 검색 등록 & SEO 구현(1)",
    date: new Date("2021-10-05"),
    content: "store/article_data/Develop/20211005_GitHubBlog_seo_1.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 5,
    title: "[GitHub Blog 개발기] SEO 구현(2) - Next.js app",
    date: new Date("2021-10-06"),
    content: "store/article_data/Develop/20211006_GitHubBlog_seo_2.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 6,
    title: "[GitHub Blog 개발기] SEO 구현(3) - Next.js app",
    date: new Date("2021-10-07"),
    content: "store/article_data/Develop/20211007_GitHubBlog_seo_3.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 7,
    title: "[GitHub Blog 개발기] sitemap, 게시글 등록 자동화 (Shell Script)",
    date: new Date("2021-10-28"),
    content: "store/article_data/Develop/20211028_GitHubBlog_auto_script.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 8,
    title: "[GitHub Blog 개발기] Markdown Index 구현 (TOC)",
    date: new Date("2022-04-05"),
    content: "store/article_data/Develop/20220405_GitHubBlog_Index.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 9,
    title: "구글 사이트맵 갱신하기",
    date: new Date("2022-05-06"),
    content: "store/article_data/Develop/20220506_Sitemap_Renew.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 10,
    title: "[GitHub Blog 개발기] 서버 마이그레이션 (AWS => 라즈베리파이 => 오라클 클라우드)",
    date: new Date("2022-05-20"),
    content: "store/article_data/Develop/20220520_GitHubBlog_Server_Migration.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 11,
    title: "MarkText, Typora를 대체할 후보?",
    date: new Date("2022-07-29"),
    content: "store/article_data/Develop/20220729_MarkText_Introduce.md",
  },
  {
    category: "Develop",
    subCategory: "",
    id: 12,
    title: "라즈베리파이에 접속하기 (Ubuntu 20.04.4 LTS)",
    date: new Date("2022-08-25"),
    content: "store/article_data/Develop/20220825_Access_to_RaspberryPi4_Ubuntu.md",
  },
];

const Develop_SubCategory = [];

export { Develop,  Develop_SubCategory };

