const Web = [
  {
    category: "Web",
    subCategory: "",
    id: 0,
    title: "[Spring] Bean이란?",
    date: new Date("2021-10-13"),
    content: "store/article_data/Web/20211013_Spring_Bean.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 1,
    title: "[Spring] 의존 객체 자동 주입이란?",
    date: new Date("2021-10-17"),
    content: "store/article_data/Web/20211017_Spring_Automatic_Dependency_Injection.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 2,
    title: "[TIP] a 태그 줄바꿈 문제",
    date: new Date("2021-10-18"),
    content: "store/article_data/Web/20211018_a_tag_word_break.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 3,
    title: "[Spring Boot 프로젝트] 프로젝트 생성하기 (Eclipse)",
    date: new Date("2021-10-29"),
    content: "store/article_data/Web/20211029_SpringBoot_AWS.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 4,
    title: "[Spring] 생명주기 (Life Cycle)",
    date: new Date("2021-11-04"),
    content: "store/article_data/Web/20211104_Spring_Life_Cycle.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 5,
    title: "[Spring] Spring 설정 - Java Config",
    date: new Date("2021-11-09"),
    content: "store/article_data/Web/20211109_Spring_Setting_w_Annotation.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 6,
    title: "[Spring] Spring Project 시작",
    date: new Date("2021-11-14"),
    content: "store/article_data/Web/20211114_Spring_Web_Service.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 7,
    title: "[Spring] Spring Project 구조",
    date: new Date("2021-11-15"),
    content: "store/article_data/Web/20211115_Spring_Project_Structure.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 8,
    title: "[Spring] UTF-8 한글 인코딩 설정, Service 객체",
    date: new Date("2021-11-19"),
    content: "store/article_data/Web/20211119_Spring_Encofing_Service_Dao.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 9,
    title: "[Spring] Controller 객체",
    date: new Date("2021-11-30"),
    content: "store/article_data/Web/20211130_Spring_Controller.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 10,
    title: "[Spring] 세션 & 쿠키",
    date: new Date("2021-12-16"),
    content: "store/article_data/Web/20211216_Spring_Session_Cookie.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 11,
    title: "[Spring] 리다이렉트 & 인터셉터",
    date: new Date("2021-12-18"),
    content: "store/article_data/Web/20211218_Spring_Redirect_Intercept.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 12,
    title: "[Spring] Controller, Service, DAO, DTO, Domain",
    date: new Date("2021-12-21"),
    content: "store/article_data/Web/20211221_Spring_Controller_Service_Dao_Dto_Domain.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 13,
    title: "[Spring] Database",
    date: new Date("2021-12-26"),
    content: "store/article_data/Web/20211226_Spring_Database.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 14,
    title: "[Spring] JDBC",
    date: new Date("2021-12-28"),
    content: "store/article_data/Web/20211228_Spring_JDBC.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 15,
    title: "[Spring] Connection Pool과 JDBC Template",
    date: new Date("2022-01-02"),
    content: "store/article_data/Web/20220102_Spring_JDBC_Template_DBCP.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 16,
    title: "[Spring] Build : Maven과 Gradle",
    date: new Date("2022-01-04"),
    content: "store/article_data/Web/20220104_Spring_Build.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 17,
    title: "[AWS] AWS Route53 호스팅 영역 요금",
    date: new Date("2022-02-08"),
    content: "store/article_data/Web/20220208_AWS_Route53_Hosting.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 18,
    title: "[Spring] JNDI",
    date: new Date("2022-03-09"),
    content: "store/article_data/Web/20220309_Spring_JNDI.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 19,
    title: "비밀번호",
    date: new Date("2022-03-24"),
    content: "store/article_data/Web/20220324_Secure_Password.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 20,
    title: "[Spring Boot 프로젝트] 스프링 코드 구조 알아보기",
    date: new Date("2022-04-17"),
    content: "store/article_data/Web/20220417_SpringBoot_AWS_Structure.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 21,
    title: "클린 아키텍처 연습 (SpringBoot)",
    date: new Date("2022-06-14"),
    content: "store/article_data/Web/20220614_Clean_Architecture.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 22,
    title: "JPA 영속성 컨텍스트",
    date: new Date("2022-08-14"),
    content: "store/article_data/Web/20220814_JPA_Persistence_Context.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 23,
    title: "Java Thread.run()과 Thread.start()의 차이",
    date: new Date("2023-01-23"),
    content: "store/article_data/Web/20230123_Java_Thread_Run_Start.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 24,
    title: "동시성 관리 (Java, DB Lock)",
    date: new Date("2023-08-17"),
    content: "store/article_data/Web/20230817_Synchronization.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 25,
    title: "Pinpoint - Client IP(REMOTE_ADDRESS) 172.17.0.1",
    date: new Date("2023-12-16"),
    content: "store/article_data/Web/20231216_Pinpoint_Address.md",
  },
  {
    category: "Web",
    subCategory: "",
    id: 26,
    title: "N+1 문제 해결 - Entity Graph",
    date: new Date("2023-12-17"),
    content: "store/article_data/Web/20231217_JPA_Entity_Graph.md",
  },
];

const Web_SubCategory = [];

export { Web,  Web_SubCategory };

