const Web = [
  {
    category: "Web",
    id: 0,
    title: "[Spring] Bean이란?",
    date: new Date("2021-10-13"),
    content: "store/article_data/Web/20211013_Spring_Bean.md",
  },
  {
    category: "Web",
    id: 1,
    title: "[Spring] 의존 객체 자동 주입이란?",
    date: new Date("2021-10-17"),
    content: "store/article_data/Web/20211017_Spring_Automatic_Dependency_Injection.md",
  },
  {
    category: "Web",
    id: 2,
    title: "[TIP] a 태그 줄바꿈 문제",
    date: new Date("2021-10-18"),
    content: "store/article_data/Web/20211018_a_tag_word_break.md",
  },
  {
    category: "Web",
    id: 3,
    title: "[Spring Boot 프로젝트] 프로젝트 생성하기 (Eclipse)",
    date: new Date("2021-10-29"),
    content: "store/article_data/Web/20211029_SpringBoot_AWS.md",
  },
  {
    category: "Web",
    id: 4,
    title: "[Spring] 생명주기 (Life Cycle)",
    date: new Date("2021-11-04"),
    content: "store/article_data/Web/20211104_Spring_Life_Cycle.md",
  },
  {
    category: "Web",
    id: 5,
    title: "[Spring] Spring 설정 - Java Config",
    date: new Date("2021-11-09"),
    content: "store/article_data/Web/20211109_Spring_Setting_w_Annotation.md",
  },
  {
    category: "Web",
    id: 6,
    title: "[Spring] Spring Project 시작",
    date: new Date("2021-11-14"),
    content: "store/article_data/Web/20211114_Spring_Web_Service.md",
  },
  {
    category: "Web",
    id: 7,
    title: "[Spring] Spring Project 구조",
    date: new Date("2021-11-15"),
    content: "store/article_data/Web/20211115_Spring_Project_Structure.md",
  },
  {
    category: "Web",
    id: 8,
    title: "[Spring] UTF-8 한글 인코딩 설정, Service 객체",
    date: new Date("2021-11-19"),
    content: "store/article_data/Web/20211119_Spring_Encofing_Service_Dao.md",
  },
  {
    category: "Web",
    id: 9,
    title: "[Spring] Controller 객체",
    date: new Date("2021-11-30"),
    content: "store/article_data/Web/20211130_Spring_Controller.md",
  },
  {
    category: "Web",
    id: 10,
    title: "[Spring] 세션 & 쿠키",
    date: new Date("2021-12-16"),
    content: "store/article_data/Web/20211216_Spring_Session_Cookie.md",
  },
  {
    category: "Web",
    id: 11,
    title: "[Spring] 리다이렉트 & 인터셉터",
    date: new Date("2021-12-18"),
    content: "store/article_data/Web/20211218_Spring_Redirect_Intercept.md",
  },
  {
    category: "Web",
    id: 12,
    title: "[Spring] Controller, Service, DAO, DTO, Domain",
    date: new Date("2021-12-21"),
    content: "store/article_data/Web/20211221_Spring_Controller_Service_Dao_Dto_Domain.md",
  },
  {
    category: "Web",
    id: 13,
    title: "[Spring] Database",
    date: new Date("2021-12-26"),
    content: "store/article_data/Web/20211226_Spring_Database.md",
  },
  {
    category: "Web",
    id: 14,
    title: "[Spring] JDBC",
    date: new Date("2021-12-28"),
    content: "store/article_data/Web/20211228_Spring_JDBC.md",
  },
  {
    category: "Web",
    id: 15,
    title: "[Spring] Build : Maven과 Gradle",
    date: new Date("2021-12-30"),
    content: "store/article_data/Web/20211230_Spring_Build.md",
  },
];

export default Web;

